apiVersion: v2
type: application
name: field-tm
description: Field Tasking Manager - coordinated field mapping.
version: "0.5.0"
appVersion: "2026.2.0"
maintainers:
- email: sam.woodcock@hotosm.org
  name: Sam Woodcock
home: https://github.com/hotosm/field-tm/tree/main/chart
icon: https://field.hotosm.org/favicon.png
