repos:
  # Versioning: Commit messages & changelog
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # Autoformat: Python code
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        files: ^src/backend/(?:.*/)*.*$
        args: [--target-version=py39]

  # Lint / autoformat: Python code
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.1.13"
    hooks:
      - id: ruff
        files: ^src/backend/(?:.*/)*.*$
        args: [--fix, --exit-non-zero-on-fix]

  # Autoformat: YAML, JSON, Markdown, etc.
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        args:
          [
            --ignore-unknown,
            --no-error-on-unmatched-pattern,
            "!chart/**",
            "!CHANGELOG.md",
            "!CONTRIBUTING.md",
            "!LICENSE.md",
            "!src/frontend/pnpm-lock.yaml",
          ]

  # Lint: Dockerfile
  - repo: https://github.com/hadolint/hadolint.git
    rev: v2.12.1-beta
    hooks:
      - id: hadolint-docker
        entry: hadolint/hadolint:v2.8.0 hadolint
        args:
          [
            "--ignore=DL3008",
            "--ignore=DL3013",
            "--ignore=DL3018",
            "--ignore=DL3059",
          ]

  # Lint: Bash scripts
  - repo: https://github.com/openstack-dev/bashate.git
    rev: 2.1.1
    hooks:
      - id: bashate
        args: ["--ignore=E006"]

  # Lint: Shell scripts
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        args: ["-x", "--exclude=SC1091"]

  # Lint: Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint
        args:
          [
            --fix,
            --disable,
            MD033,
            --ignore,
            LICENSE.md,
            --ignore,
            CHANGELOG.md,
            --ignore,
            .github,
          ]
