# Copyright (c) Humanitarian OpenStreetMap Team
# This file is part of Field-TM.
#
#     Field-TM is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     Field-TM is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with Field-TM.  If not, see <https:#www.gnu.org/licenses/>.
#

# For testing the entire stack, with only the required services

name: field-tm-test

volumes:
  ftm_db_data:
  ftm_logs:
  central_db_data:
  central_frontend:

networks:
  ftm-net:
    name: field-tm-test

services:
  # Frontend tests may rely on the proxy, at some point
  # proxy:
  #   extends:
  #     file: compose.yaml
  #     service: proxy

  # Remove qfield dependencies
  backend:
    extends:
      file: compose.yaml
      service: backend
    volumes: !override
      - ftm_logs:/opt/logs
      # No mounts needed, as we do a re-built before every test run
    # We don't need proxy
    depends_on: !override
      fieldtm-db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
      central:
        condition: service_healthy
        required: false

  # ui:
  #   extends:
  #     file: compose.yaml
  #     service: ui

  # Required for ODK Central user creation (sends welcome email on POST /v1/users)
  mail:
    extends:
      file: compose.yaml
      service: mail

  central:
    extends:
      file: compose.yaml
      service: central
    # We don't need proxy or pyxform
    depends_on: !override
      central-db:
        condition: service_healthy
      mail:
        condition: service_started

  migrations:
    extends:
      file: compose.yaml
      service: migrations

  fieldtm-db:
    extends:
      file: compose.yaml
      service: fieldtm-db
    ports: []

  central-db:
    extends:
      file: compose.yaml
      service: central-db
    ports: []
