site_name: FMTM
site_description: Coordinated field mapping for Open Mapping campaigns.
# strict: true
site_url: "https://docs.fmtm.dev/"

repo_name: "hotosm/fmtm"
repo_url: "https://github.com/hotosm/fmtm/"
edit_uri: "edit/main/docs/"

extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/hotosm/"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/hotosm"
    - icon: "fontawesome/solid/globe"
      link: "https://www.hotosm.org"
  copyright: Copyright &copy; 2010 HOTOSM
  generator: false

theme:
  name: material
  palette:
    primary: custom
  language: en
  favicon: images/favicon.png
  logo: images/hot_logo.png

extra_css:
  - css/extra.css
  - css/timeline.css

markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: Page contents
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.extra
  - pymdownx.emoji:
  - pymdownx.tabbed:
      alternate_style: true
  - mdx_truly_sane_lists

plugins:
  - search
  - git-revision-date-localized
  - exclude:
      glob:
        - plugins/*
        - __pycache__/*
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            members_order: source
            separate_signature: true
            filters: ["!^_"]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true

nav:
  - Home: index.md
  - Get Started:
      - About: about/about.md
      - Installation: INSTALL.md
      - Contribution Guidelines: CONTRIBUTING.md
      - Code of Conduct: https://docs.hotosm.org/code-of-conduct
      - FAQ: about/faq.md
      - The Team: about/team.md
  - User Manuals:
      - Mapper Guide: manuals/mapping.md
      - Project Manager Guide: manuals/project-managers.md
      - Video Guides: manuals/videos.md
      - User Types Explanation: manuals/user-breakdown.md
      - Workflow Diagrams: manuals/workflow-diagrams.md
      - XLSForm Design: manuals/xlsform-design.md
      - Field Mapping Examples: manuals/field-mapping-examples.md
      - Visualising Data Externally: https://docs.getodk.org/tutorial-mapping-households
      - ODKCollect Offline Maps: https://docs.getodk.org/collect-offline-maps
  - Developer Guide:
      - Dev Practices: https://docs.hotosm.org/dev-practices
      - Setup: dev/Setup.md
      - Backend: dev/Backend.md
      - Frontend: dev/Frontend.md
      - Production Deployment: dev/Production.md
      - Database Tips: dev/Database-Tips.md
      - Troubleshooting: dev/Troubleshooting.md
      - Pre-Commit: https://docs.hotosm.org/dev-guide/repo-management/pre-commit/
      - Versioning: https://docs.hotosm.org/dev-guide/repo-management/version-control/#creating-releases
      - Class Hierarchy: apidocs/html/inherits.html
      - Code Coverage: coverage.html
  - Utilities:
      - XLSForm Converter: https://getodk.org/xlsform/
      - QRCode Converter: qrcode-util.md
      - Helpers: https://api.stage.fmtm.hotosm.org/docs#/helper
  - Example XLSForms: example-xlsforms/README.md
  - Roadmap:
      - User: https://github.com/hotosm/fmtm?tab=readme-ov-file#roadmap
      - Development: https://roadmap.fmtm.dev
      - Task Board: https://github.com/orgs/hotosm/projects/22/views/1?sliceBy%5BcolumnId%5D=Milestone
  - Timeline: timeline.md
  - API Docs: https://hotosm.github.io/swagger/?url=https://docs.fmtm.dev/openapi.json
