apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "field-tm.fullname" . }}
  labels:
    {{- include "field-tm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "field-tm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "field-tm.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "field-tm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- if .Values.db.enabled }}
        - name: db-check
          image: {{ .Values.db.image.registry }}/{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}
          imagePullPolicy: IfNotPresent
          env:
            - name: FTM_DB_HOST
              value: {{ if .Values.backend.dbHostOverride }}{{ .Values.backend.dbHostOverride | quote }}{{ else }}{{ printf "%s-db" .Release.Name | quote }}{{ end }}
          command:
            - /bin/bash
            - -c
            - |
              until pg_isready -h "$FTM_DB_HOST"; do
                  echo "waiting for database to be ready";
                  sleep 2;
              done;
        {{- end }}
        - name: migrations
          image: "{{ .Values.image.repository }}/backend:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: FTM_DB_HOST
              value: {{ if .Values.backend.dbHostOverride }}{{ .Values.backend.dbHostOverride | quote }}{{ else }}{{ printf "%s-db" .Release.Name | quote }}{{ end }}
          envFrom:
            {{- toYaml .Values.backend.extraEnvFrom | nindent 12 }}
          command: ["/migrate-entrypoint.sh"]
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}/backend:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.backend.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.backend.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          env:
            - name: FTM_DOMAIN
              value: {{ .Values.domain | quote }}
            - name: FTM_DB_HOST
              value: {{ if .Values.backend.dbHostOverride }}{{ .Values.backend.dbHostOverride | quote }}{{ else }}{{ printf "%s-db" .Release.Name | quote }}{{ end }}
          envFrom:
            {{- toYaml .Values.backend.extraEnvFrom | nindent 12 }}
          volumeMounts:
          {{- with .Values.backend.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.backend.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
