networks:
  fmtm-local:
    external: true

services:
  k6:
    container_name: k6-load-test
    image: docker.io/grafana/k6:0.58.0
    volumes:
      - ./load-test.js:/load-test.js
    networks:
      - fmtm-local
    restart: unless-stopped
