export const projectDetailsConstant = {
  id: 505,
  name: 'Freetown CBD Regeneration - POI Mapping Phase-3',
  field_mapping_app: 'ODK',
  outline: {},
  odkid: 441,
  author_sub: 'osm|4610340',
  organisation_id: 1,
  short_description: 'Freetown CBD Regeneration - POI Mapping Phase-3',
  description: 'Freetown CBD Regeneration - POI Mapping Phase-3',
  per_task_instructions:
    '<p><strong>Upon arriving at a building:</strong></p><ul><li><p>Identify a respondent</p></li><li><p>Introduce yourself</p></li><li><p>Provide a summary description of the project (Reference project description in the form)</p></li><li><p>Once you complete the form, proofread your responses before submitting</p></li></ul>',
  slug: 'freetown-cbd-regeneration-poi-mapping-phase-3',
  task_split_type: 'DIVIDE_ON_SQUARE',
  location_str: 'Freetown,Sierra Leone',
  custom_tms_url: '',
  status: 'PUBLISHED',
  visibility: 'PRIVATE',
  osm_category: 'OSM Buildings',
  odk_form_id: 'fcc_pform_final',
  odk_form_xml: '',
  mapper_level: 'INTERMEDIATE',
  priority: 'MEDIUM',
  featured: false,
  odk_central_url: 'https://odk.hotosm.org/',
  odk_central_user: 'sam.woodcock@protonmail.com',
  odk_token:
    'https://odk.hotosm.org/v1/key/raLwtd!uW242CTviDxD!Tsc3howszYhDbcRy0kI5HsxzKFPf0yzPJ!OFClSLPNMK/projects/441',
  data_extract_url: 'https://s3.fmtm.hotosm.org/fmtm-data/1/505/data_extract.fgb',
  task_split_dimension: 200,
  task_num_buildings: null,
  primary_geom_type: 'POLYGON',
  new_geom_type: 'POLYGON',
  geo_restrict_distance_meters: 50,
  geo_restrict_force_error: false,
  use_odk_collect: true,
  hashtags: ['#Field-TM', '#fmtm.hotosm.org-505'],
  due_date: null,
  updated_at: '2025-11-26T12:09:47.328468Z',
  created_at: '2025-11-26T12:09:47.328468Z',
  tasks: [],
  organisation_name: 'HOTOSM',
  organisation_logo: 'https://avatars.githubusercontent.com/u/458752?s=280&v=4',
  centroid: {
    type: 'Point',
    coordinates: [-13.243547911, 8.4736427],
  },
  bbox: [-13.252861, 8.461819, -13.230435, 8.479638],
  last_active: null,
  total_tasks: 52,
  num_contributors: null,
  total_submissions: 0,
  tasks_mapped: 0,
  tasks_validated: 0,
  tasks_bad: 0,
  project_url: null,
  qfield_project_id: null,
};
