# Copyright (c) Humanitarian OpenStreetMap Team
# This file is part of FMTM.
#
#     FMTM is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     FMTM is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with FMTM.  If not, see <https:#www.gnu.org/licenses/>.
#

name: fmtm-dev

volumes:
  fmtm_frontend:
    name: fmtm-frontend-${GIT_BRANCH}
  fmtm_mapper_frontend:
    name: fmtm-mapper-frontend-${GIT_BRANCH}
  fmtm_db_data:
    name: fmtm-db-data-${GIT_BRANCH}
  fmtm_data:
    name: fmtm-s3-data-${GIT_BRANCH}
  fmtm_logs:
    name: fmtm-logs-${GIT_BRANCH}
  fmtm_images:
    name: fmtm-images-${GIT_BRANCH}
  fmtm_tiles:
    name: fmtm-tiles-${GIT_BRANCH}
  certs:
    name: fmtm-certs-${GIT_BRANCH}
  central_db_data:
    name: fmtm-central-db-data-${GIT_BRANCH}
  central_frontend:
    name: fmtm-central-frontend-${GIT_BRANCH}

networks:
  fmtm-net:
    name: fmtm-${GIT_BRANCH}
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24

services:
  proxy:
    image: "bunkerity/bunkerweb-all-in-one:${BUNKERWEB_TAG:-1.6.2-rc1}"
    depends_on:
      # Frontends must be built and available first
      ui:
        condition: service_completed_successfully
      central-ui:
        condition: service_completed_successfully
    volumes:
      # - certs:/etc/letsencrypt
      - certs:/data
      - fmtm_frontend:/var/www/html/dev.fmtm.hotosm.org:ro
      - fmtm_mapper_frontend:/var/www/html/mapper.dev.fmtm.hotosm.org:ro
      - central_frontend:/var/www/html/odk.dev.fmtm.hotosm.org:ro
    environment:
      # General
      BUNKERWEB_INSTANCES: proxy:5000
      LOG_LEVEL: notice
      USE_BUNKERNET: no
      DISABLE_DEFAULT_SERVER: yes
      API_WHITELIST_IP: 127.0.0.0/8 10.20.30.0/24
      # Avoid running ModSec rules on internal service calls
      WHITELIST_IP: 10.20.30.0/24
      WHITELIST_URI: https://dev.fmtm.hotosm.org
      MULTISITE: yes
      USE_REVERSE_PROXY: yes
      # Required for electric headers electric-offset, electric-handle, electric-schema, electric-cursor
      KEEP_UPSTREAM_HEADERS: yes
      REVERSE_PROXY_INTERCEPT_ERRORS: no
      ALLOWED_METHODS: OPTIONS|HEAD|GET|POST|PATCH|PUT|DELETE
      USE_REAL_IP: yes
      SERVE_FILES: yes
      USE_BACKUP: no
      USE_METRICS: no
      # USE_ANTIBOT: yes
      USE_LIMIT_CONN: yes
      # BAD_BEHAVIOUR disabled as it's difficult to work with...
      USE_BAD_BEHAVIOR: no
      USE_LIMIT_REQ: yes
      USE_MODSECURITY: yes
      USE_GZIP: yes
      # On client, brotli is preferred over gzip if both are enabled
      USE_BROTLI: yes
      # For OpenTelemetry (Allow-Headers are what the browser can include in the REQUEST headers)
      CUSTOM_HEADER: "Access-Control-Allow-Headers: DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,traceparent,tracestate"
      AUTO_LETS_ENCRYPT: yes
      EMAIL_LETS_ENCRYPT: ${CERT_EMAIL}
      # USE_LETS_ENCRYPT_STAGING: yes
      # Reverse proxy configs
      SERVER_NAME: dev.fmtm.hotosm.org mapper.dev.fmtm.hotosm.org api.dev.fmtm.hotosm.org s3.dev.fmtm.hotosm.org sync.dev.fmtm.hotosm.org odk.dev.fmtm.hotosm.org
      # We need this to allow for client-side routing in the SPA (from index.html)
      dev.fmtm.hotosm.org_ERRORS: 404=/index.html
      mapper.dev.fmtm.hotosm.org_ERRORS: 404=/index.html
      # CORS for the backend is configured by FastAPI
      api.dev.fmtm.hotosm.org_REVERSE_PROXY_HOST: http://api:8000
      api.dev.fmtm.hotosm.org_MAX_CLIENT_SIZE: 1G
      # Increase timeout slightly for long project creation requests
      api.dev.fmtm.hotosm.org_REVERSE_PROXY_READ_TIMEOUT: 90s
      s3.dev.fmtm.hotosm.org_REVERSE_PROXY_HOST: http://s3:9000
      s3.dev.fmtm.hotosm.org_MAX_CLIENT_SIZE: 10G
      # CORS must be enabled for Minio to work
      s3.dev.fmtm.hotosm.org_USE_CORS: yes
      s3.dev.fmtm.hotosm.org_CORS_ALLOW_ORIGIN: https://dev.fmtm.hotosm.org
      sync.dev.fmtm.hotosm.org_REVERSE_PROXY_HOST: http://electric:3000
      sync.dev.fmtm.hotosm.org_MAX_CLIENT_SIZE: 1G
      # CORS must be enabled for Electric to work
      sync.dev.fmtm.hotosm.org_USE_CORS: yes
      sync.dev.fmtm.hotosm.org_CORS_ALLOW_ORIGIN: https://mapper.dev.fmtm.hotosm.org
      sync.dev.fmtm.hotosm.org_CORS_ALLOW_METHODS: GET, HEAD, DELETE, OPTIONS
      # Expose-Headers are RESPONSE headers the browser is allowed to access
      sync.dev.fmtm.hotosm.org_CORS_EXPOSE_HEADERS: electric-offset,electric-handle,electric-schema,electric-cursor,electric-up-to-date
      odk.dev.fmtm.hotosm.org_REVERSE_PROXY_HOST: http://central:8383
      odk.dev.fmtm.hotosm.org_REVERSE_PROXY_URL: ~ ^/v\d
      # buffer requests, but not responses, so streaming out works
      odk.dev.fmtm.hotosm.org_REVERSE_PROXY_BUFFERING: no
      odk.dev.fmtm.hotosm.org_MAX_CLIENT_SIZE: 1G
    ports:
      - 80:8080
      - 443:8443
    networks:
      - fmtm-net
    restart: "unless-stopped"

  api:
    image: "ghcr.io/hotosm/fmtm/backend:${GIT_BRANCH}"
    volumes:
      - fmtm_logs:/opt/logs
    depends_on:
      proxy:
        condition: service_healthy
      fmtm-db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
      s3:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - fmtm-net
    restart: "unless-stopped"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/__lbheartbeat__"]
      start_period: 60s
      interval: 10s
      timeout: 5s
      retries: 10
    deploy:
      replicas: ${API_REPLICAS:-2}
      resources:
        limits:
          cpus: "0.9"
          memory: 1500M
        reservations:
          cpus: "0.1"
          memory: 100M

  ui:
    # This service simply builds the frontend to a volume
    # accessible to the proxy, then shuts down
    image: "ghcr.io/hotosm/fmtm/frontend:${GIT_BRANCH:-development}"
    build:
      context: ../src
      dockerfile: Dockerfile.ui.prod
      args:
        APP_VERSION: ${GIT_BRANCH}
        VITE_API_URL: https://${FMTM_API_DOMAIN:-api.${FMTM_DOMAIN}}
        VITE_SYNC_URL: https://${FMTM_SYNC_DOMAIN:-sync.${FMTM_DOMAIN}}
        VITE_S3_URL: https://${FMTM_SYNC_DOMAIN:-sync.${FMTM_DOMAIN}}
    volumes:
      - fmtm_frontend:/frontend/manager
      - fmtm_mapper_frontend:/frontend/mapper
    network_mode: none
    restart: "on-failure:2"

  central:
    image: "ghcr.io/hotosm/fmtm/odkcentral:${ODK_CENTRAL_TAG:-v2024.3.1}"
    depends_on:
      proxy:
        condition: service_healthy
      central-db:
        condition: service_healthy
      s3:
        condition: service_healthy
      pyxform:
        condition: service_started
    environment:
      - DOMAIN=${FMTM_ODK_DOMAIN:-odk.${FMTM_DOMAIN}}
      - SSL_TYPE=upstream
      - SYSADMIN_EMAIL=${ODK_CENTRAL_USER}
      - SYSADMIN_PASSWD=${ODK_CENTRAL_PASSWD}
      - HTTPS_PORT=443
      - DB_HOST=${CENTRAL_DB_HOST:-central-db}
      - DB_USER=${CENTRAL_DB_USER}
      - DB_PASSWORD=${CENTRAL_DB_PASSWORD}
      - DB_NAME=${CENTRAL_DB_NAME}
      - DB_SSL=null
      - EMAIL_FROM=${ODK_CENTRAL_USER}
      - EMAIL_HOST=${EMAIL_HOST:-mail}
      - EMAIL_PORT=${EMAIL_PORT:-25}
      - EMAIL_SECURE=${EMAIL_SECURE:-false}
      - EMAIL_IGNORE_TLS=${EMAIL_IGNORE_TLS:-true}
      - EMAIL_USER=${EMAIL_USER:-''}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD:-''}
      - OIDC_ENABLED=${OIDC_ENABLED:-false}
      - SENTRY_ORG_SUBDOMAIN=${SENTRY_ORG_SUBDOMAIN:-o130137}
      - SENTRY_KEY=${SENTRY_KEY:-3cf75f54983e473da6bd07daddf0d2ee}
      - SENTRY_PROJECT=${SENTRY_PROJECT:-1298632}
      - S3_SERVER=${S3_ENDPOINT}
      - S3_BUCKET_NAME=${S3_ODK_BUCKET_NAME:-"fmtm-odk-media"}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
    networks:
      - fmtm-net
    restart: "unless-stopped"
    healthcheck:
      test: nc -z localhost 8383 || exit 1
      start_period: 15s
      interval: 10s
      timeout: 5s
      retries: 10

  central-webhook:
    image: "ghcr.io/hotosm/central-webhook:${ODK_WEBHOOK_TAG:-0.1.0-rc}"
    depends_on:
      central:
        condition: service_healthy
    environment:
      CENTRAL_WEBHOOK_DB_URI: postgresql://${CENTRAL_DB_USER}:${CENTRAL_DB_PASSWORD}@central-db:5432/${CENTRAL_DB_NAME}?sslmode=disable
      CENTRAL_WEBHOOK_UPDATE_ENTITY_URL: http://api:8000/integrations/webhooks/entity-status
      # CENTRAL_WEBHOOK_REVIEW_SUBMISSION_URL: http://api:8000/integrations/webhooks/entity-status
      CENTRAL_WEBHOOK_API_KEY: ${CENTRAL_WEBHOOK_API_KEY}
      CENTRAL_WEBHOOK_LOG_LEVEL: ${CENTRAL_WEBHOOK_LOG_LEVEL:-INFO}
    networks:
      - fmtm-net
    restart: "unless-stopped"

  pyxform:
    image: "ghcr.io/getodk/pyxform-http:v3.0.0"
    networks:
      - fmtm-net
    restart: "unless-stopped"

  central-ui:
    # This service simply builds the frontend to a volume
    # accessible to the proxy, then shuts down
    image: "ghcr.io/hotosm/fmtm/odkcentral-ui:${ODK_CENTRAL_TAG:-v2024.3.1}"
    volumes:
      - central_frontend:/frontend
    network_mode: none
    restart: "on-failure:2"

  s3:
    image: "docker.io/minio/minio:${MINIO_TAG:-RELEASE.2025-01-20T14-49-07Z}"
    depends_on:
      proxy:
        condition: service_started
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
      MINIO_VOLUMES: "/mnt/data"
      MINIO_BROWSER: "off"
    volumes:
      - fmtm_data:/mnt/data
    networks:
      - fmtm-net
    command: minio server
    restart: "unless-stopped"
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 5s
      retries: 3
      start_period: 5s
      timeout: 5s

  fmtm-db:
    image: "ghcr.io/hotosm/postgis:${POSTGIS_TAG:-14-3.5-alpine}"
    command: -c 'max_connections=300' -c 'wal_level=logical'
    volumes:
      - fmtm_db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${FMTM_DB_USER}
      - POSTGRES_PASSWORD=${FMTM_DB_PASSWORD}
      - POSTGRES_DB=${FMTM_DB_NAME}
    ports:
      - "5433:5432"
    networks:
      - fmtm-net
    restart: "unless-stopped"
    healthcheck:
      test: pg_isready -U ${FMTM_DB_USER} -d ${FMTM_DB_NAME}
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 3

  electric:
    image: "electricsql/electric:${ELECTRIC_TAG:-1.0.4}"
    depends_on:
      proxy:
        condition: service_started
      fmtm-db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: postgresql://${FMTM_DB_USER}:${FMTM_DB_PASSWORD}@${FMTM_DB_HOST:-fmtm-db}/${FMTM_DB_NAME:-fmtm}?sslmode=disable
      # Do not set ELECTRIC_SECRET var for now, until docs are available for how it actually works...
      # The frontend ShapeStream should then use params.api_secret? Or perhaps set via proxy somehow?
      ELECTRIC_INSECURE: true
      # OTEL_EXPORT: otlp
      # OTLP_ENDPOINT: https://...
      # ELECTRIC_WRITE_TO_PG_MODE: direct_writes
    networks:
      - fmtm-net
    restart: "unless-stopped"

  central-db:
    image: "ghcr.io/hotosm/postgis:${POSTGIS_TAG:-14-3.5-alpine}"
    volumes:
      - central_db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${CENTRAL_DB_USER}
      - POSTGRES_PASSWORD=${CENTRAL_DB_PASSWORD}
      - POSTGRES_DB=${CENTRAL_DB_NAME}
    ports:
      - "5434:5432"
    networks:
      - fmtm-net
    restart: "unless-stopped"
    healthcheck:
      test: pg_isready -U ${CENTRAL_DB_USER} -d ${CENTRAL_DB_NAME}
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 3

  migrations:
    image: "ghcr.io/hotosm/fmtm/backend:${GIT_BRANCH}"
    depends_on:
      proxy:
        condition: service_healthy
      fmtm-db:
        condition: service_healthy
      s3:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - fmtm-net
    entrypoint: ["/migrate-entrypoint.sh"]
    restart: "on-failure:2"

  scheduler:
    extends:
      file: ../compose.yaml
      service: scheduler
    image: "ghcr.io/hotosm/fmtm/backend:${GIT_BRANCH}"
