# Copyright (c) 2022, 2023 Humanitarian OpenStreetMap Team
# This file is part of FMTM.
#
#     FMTM is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     FMTM is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with FMTM.  If not, see <https:#www.gnu.org/licenses/>.
#

name: fmtm-main

volumes:
  fmtm_frontend:
    name: fmtm-frontend-main
  fmtm_db_data:
    name: fmtm-db-data-main
  fmtm_data:
    name: fmtm-s3-data-main
  fmtm_logs:
    name: fmtm-logs-main
  fmtm_images:
    name: fmtm-images-main
  fmtm_tiles:
    name: fmtm-tiles-main
  certs:
    name: fmtm-certs-main
  certbot_data:
    name: fmtm-certbot-data-main

networks:
  fmtm-net:
    name: fmtm-main

services:
  proxy:
    image: "ghcr.io/hotosm/fmtm/proxy:main"
    depends_on:
      api:
        condition: service_started
      certbot:
        condition: service_completed_successfully
      s3:
        condition: service_healthy
      ui:
        condition: service_completed_successfully
      electric:
        condition: service_started
    volumes:
      - fmtm_frontend:/usr/share/nginx/html/fmtm
      - certs:/etc/letsencrypt
      - certbot_data:/var/www/certbot
    environment:
      FMTM_DOMAIN: ${FMTM_DOMAIN}
      FMTM_API_DOMAIN: ${FMTM_API_DOMAIN:-api.${FMTM_DOMAIN}}
      FMTM_S3_DOMAIN: ${FMTM_S3_DOMAIN:-s3.${FMTM_DOMAIN}}
      FMTM_SYNC_DOMAIN: ${FMTM_SYNC_DOMAIN:-sync.${FMTM_DOMAIN}}
    ports:
      - 80:80
      - 443:443
    networks:
      - fmtm-net
    restart: "unless-stopped"

  api:
    extends:
      file: compose.staging.yaml
      service: api

  ui:
    extends:
      file: compose.staging.yaml
      service: ui

  s3:
    extends:
      file: compose.staging.yaml
      service: s3

  fmtm-db:
    extends:
      file: compose.staging.yaml
      service: fmtm-db

  electric:
    extends:
      file: compose.staging.yaml
      service: electric

  migrations:
    extends:
      file: compose.staging.yaml
      service: migrations

  scheduler:
    extends:
      file: compose.staging.yaml
      service: scheduler

  backup:
    extends:
      file: compose.staging.yaml
      service: backup
    depends_on:
      fmtm-db:
        condition: service_healthy

  certbot:
    image: "ghcr.io/hotosm/fmtm/proxy:certs-init-main"
    volumes:
      - certs:/etc/letsencrypt
      - certbot_data:/var/www/certbot
    environment:
      FMTM_DOMAIN: ${FMTM_DOMAIN}
      FMTM_API_DOMAIN: ${FMTM_API_DOMAIN:-api.${FMTM_DOMAIN}}
      FMTM_S3_DOMAIN: ${FMTM_S3_DOMAIN:-s3.${FMTM_DOMAIN}}
      FMTM_SYNC_DOMAIN: ${FMTM_SYNC_DOMAIN:-sync.${FMTM_DOMAIN}}
      CERT_EMAIL: ${CERT_EMAIL}
    ports:
      - 80:80
      - 443:443
    networks:
      - fmtm-net
    restart: "on-failure:2"
