# Uses hostname fmtm.dev.test for api and ui on same domain
# otherwise tests will not work using the cookie for auth

networks:
  fmtm-net:
    name: fmtm-${GIT_BRANCH:-local}

services:
  api:
    hostname: fmtm.dev.test
    environment:
      # Run via alias fmtm.dev.test
      FMTM_DOMAIN: "fmtm.dev.test"
      # Do not use dev port, use port 80
      FMTM_DEV_PORT: "false"
    # The ci image has overrides for CMD and ENTRYPOINT, so re-apply
    entrypoint: ["/app-entrypoint.sh"]
    # API_REPLICAS can be increased via CI env vars
    command:
      [
        "uvicorn",
        "app.main:api",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--workers",
        "1",
        "--log-level",
        "critical",
        "--no-access-log",
      ]

  ui:
    # This hostname is used for Playwright test internal networking
    hostname: fmtm.dev.test
    environment:
      VITE_API_URL: "http://fmtm.dev.test:8000"
    command: --port 80
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/80' || exit 1
      interval: 5s
      retries: 3
      start_period: 5s
      timeout: 5s

  ui-test:
    image: "mcr.microsoft.com/playwright:${PLAYWRIGHT_TAG:-v1.44.1}"
    depends_on:
      # Starts the proxy and all other services
      proxy:
        condition: service_healthy
      api:
        # Override: must be healthy before tests run
        condition: service_healthy
        # Override: must be healthy before tests run
      ui:
        condition: service_healthy
    working_dir: /app
    environment:
      DISPLAY: :0
    volumes:
      - ./src/frontend:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    entrypoint: /bin/sh -c
    command:
      - |
        npm install --legacy-peer-deps
        npm run test:e2e
    ports:
      - "9323:9323"
    networks:
      - fmtm-net
    restart: "no"
