name: Frontend Tests

on:
  workflow_call:
    paths:
      - src/frontend/**

jobs:
  test:
    name: Run Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Change this to your preferred Node.js version

      - name: Test Frontend Main
        run: |
          cd src/frontend
          npm install
          npm run test
