"""QGIS project metadata fixes (ICC, canvas, layer tree)."""

import logging
import re
import zipfile
from pathlib import Path
from typing import Optional


_DANGLING_ICC_RE = re.compile(rb'\s+iccProfileId="attachment:///([^"]+)"')


def _fix_dangling_icc_refs(
    qgs_data: bytes, bundled: set, log: logging.Logger
) -> tuple[bytes, bool]:
    """Strip iccProfileId attrs that reference attachments absent from the zip."""
    changed = False

    def _strip_if_missing(m: re.Match) -> bytes:
        nonlocal changed
        attachment_name = m.group(1).decode("utf-8")
        if attachment_name in bundled:
            return m.group(0)
        changed = True
        log.warning(
            "Removed dangling iccProfileId reference to missing attachment: %s",
            attachment_name,
        )
        return b""

    return _DANGLING_ICC_RE.sub(_strip_if_missing, qgs_data), changed


def _fix_task_layer_tree(
    qgs_data: bytes, log: logging.Logger
) -> tuple[bytes, bool]:
    """Ensure the tasks layer node appears in the layer-tree-group.

    When QGIS runs headless, addMapLayer(addToLegend=True) registers the layer
    in <projectlayers> but does not always write the corresponding
    <layer-tree-layer> node.  The missing node causes QFieldCloud's metadata
    parser to fail with "Failed to parse metadata from project", and also
    prevents the tasks layer from appearing in the QField layer panel.
    """
    # Only act if a tasks maplayer block is present in projectlayers
    tasks_block_m = re.search(
        rb"<maplayer\b[^>]*>(?:(?!</maplayer>).)*?<layername>tasks</layername>"
        rb"(?:(?!</maplayer>).)*?</maplayer>",
        qgs_data,
        re.DOTALL,
    )
    if not tasks_block_m:
        return qgs_data, False

    tasks_block = tasks_block_m.group(0)
    id_m = re.search(rb"<id>(.*?)</id>", tasks_block)
    ds_m = re.search(rb"<datasource>(.*?)</datasource>", tasks_block)
    if not id_m:
        log.warning("tasks maplayer has no <id>; skipping layer-tree fix")
        return qgs_data, False

    tasks_id = id_m.group(1).decode("utf-8")
    datasource = ds_m.group(1).decode("utf-8") if ds_m else "./tasks.gpkg"

    # Already in the tree? Nothing to do.
    if re.search(
        rb'<layer-tree-layer\b[^>]*\bid="' + re.escape(tasks_id.encode()) + rb'"',
        qgs_data,
    ):
        return qgs_data, False

    layer_tree_node = (
        f'\n    <layer-tree-layer patch_size="-1,-1" expanded="1" providerKey="ogr"'
        f' id="{tasks_id}" checked="Qt::Checked" source="{datasource}"'
        f' legend_split_behavior="0" name="tasks" legend_exp="">\n'
        f"      <customproperties>\n"
        f"        <Option />\n"
        f"      </customproperties>\n"
        f"    </layer-tree-layer>"
    ).encode()

    # Insert after the first </layer-tree-layer> (survey layer), so tasks
    # appears second in the tree - below survey but above list/basemap layers.
    ltg_m = re.search(rb"<layer-tree-group\b[^>]*>", qgs_data)
    if not ltg_m:
        log.warning("No <layer-tree-group> found; skipping layer-tree fix")
        return qgs_data, False

    first_end_m = re.search(rb"</layer-tree-layer>", qgs_data[ltg_m.end():])
    if first_end_m:
        insert_at = ltg_m.end() + first_end_m.end()
    else:
        insert_at = ltg_m.end()

    updated = qgs_data[:insert_at] + layer_tree_node + qgs_data[insert_at:]
    log.info("Injected tasks <layer-tree-layer> node into project layer tree")
    return updated, True


def _inject_map_canvas(
    qgs_data: bytes, extent_bbox: list, log: logging.Logger
) -> tuple[bytes, bool]:
    """Inject <mapcanvas name="theMapCanvas"> if absent.

    QFieldCloud's process_projectfile worker searches for this element by name
    to extract the project extent and background colour.  Projects generated by
    xlsform2qgis omit it because QGIS only writes it when a QgsMapCanvas
    object is attached (GUI context only).

    TODO remove this logic if after solved issue:
    https://github.com/opengisch/xlsform2qgis/issues/7
    """
    if b'name="theMapCanvas"' in qgs_data:
        return qgs_data, False

    # Grab the <spatialrefsys> block from <projectCrs> to reuse as <destinationsrs>
    crs_m = re.search(
        rb"<projectCrs>\s*(<spatialrefsys\b.*?</spatialrefsys>)\s*</projectCrs>",
        qgs_data,
        re.DOTALL,
    )
    if not crs_m:
        log.warning(
            "Cannot inject theMapCanvas: no <projectCrs> found in project XML"
        )
        return qgs_data, False

    srs_block = crs_m.group(1)

    # Derive map units from the CRS projection acronym
    acronym_m = re.search(rb"<projectionacronym>(.*?)</projectionacronym>", srs_block)
    acronym = acronym_m.group(1).decode() if acronym_m else ""
    units = "degrees" if acronym == "longlat" else "meters"

    xmin, ymin, xmax, ymax = extent_bbox
    canvas_xml = (
        f'\n  <mapcanvas name="theMapCanvas" annotationsVisible="1">\n'
        f"    <units>{units}</units>\n"
        f"    <extent>\n"
        f"      <xmin>{xmin}</xmin>\n"
        f"      <ymin>{ymin}</ymin>\n"
        f"      <xmax>{xmax}</xmax>\n"
        f"      <ymax>{ymax}</ymax>\n"
        f"    </extent>\n"
        f"    <rotation>0</rotation>\n"
        f"    <destinationsrs>\n"
        f"      {srs_block.decode()}\n"
        f"    </destinationsrs>\n"
        f"    <rendermaptile>0</rendermaptile>\n"
        f"  </mapcanvas>"
    ).encode()

    # Insert right after </verticalCrs> (preferred) or </projectCrs> (fallback)
    for anchor in (b"</verticalCrs>", b"</projectCrs>"):
        if anchor in qgs_data:
            updated = qgs_data.replace(anchor, anchor + canvas_xml, 1)
            log.info("Injected <mapcanvas name=\"theMapCanvas\"> into project XML")
            return updated, True

    log.warning("Could not find insertion point for theMapCanvas in project XML")
    return qgs_data, False


def _apply_qgs_metadata_fixes(
    qgs_data: bytes,
    bundled: set[str],
    log: logging.Logger,
    extent_bbox: Optional[list] = None,
) -> tuple[bytes, bool]:
    """Apply all in-memory metadata fixes to a qgs payload."""
    qgs_data, icc_changed = _fix_dangling_icc_refs(qgs_data, bundled, log)
    qgs_data, tree_fixed = _fix_task_layer_tree(qgs_data, log)

    if extent_bbox is not None:
        qgs_data, canvas_injected = _inject_map_canvas(qgs_data, extent_bbox, log)
    else:
        canvas_injected = False
        if b'name="theMapCanvas"' not in qgs_data:
            log.warning(
                "Project has no <mapcanvas name=\"theMapCanvas\"> and no "
                "extent_bbox was provided; QFieldCloud may fail to parse metadata"
            )

    return qgs_data, icc_changed or tree_fixed or canvas_injected


def _sanitize_qgz_project(
    project_path: Path, log: logging.Logger, extent_bbox: Optional[list] = None
) -> None:
    """Patch metadata inside a qgz archive when fixes are needed."""
    with zipfile.ZipFile(project_path, "r") as archive:
        entry_names = archive.namelist()
        bundled = set(entry_names)
        qgs_entries = [name for name in entry_names if name.lower().endswith(".qgs")]
        if not qgs_entries:
            log.warning("No .qgs entry found inside %s", project_path)
            return
        qgs_entry = qgs_entries[0]
        qgs_data = archive.read(qgs_entry)

    qgs_data, changed = _apply_qgs_metadata_fixes(qgs_data, bundled, log, extent_bbox)
    if not changed:
        return

    temp_archive = project_path.with_suffix(project_path.suffix + ".tmp")
    with zipfile.ZipFile(project_path, "r") as src, zipfile.ZipFile(
        temp_archive, "w", compression=zipfile.ZIP_DEFLATED
    ) as dst:
        for entry_name in entry_names:
            if entry_name == qgs_entry:
                dst.writestr(entry_name, qgs_data)
                continue
            dst.writestr(entry_name, src.read(entry_name))

    temp_archive.replace(project_path)
    log.info("Patched project metadata in %s", project_path)


def _sanitize_qgs_project(
    project_path: Path, log: logging.Logger, extent_bbox: Optional[list] = None
) -> None:
    """Patch metadata in a plain qgs project when fixes are needed."""
    qgs_data = project_path.read_bytes()
    qgs_data, changed = _apply_qgs_metadata_fixes(qgs_data, set(), log, extent_bbox)
    if not changed:
        return

    project_path.write_bytes(qgs_data)
    log.info("Patched project metadata in %s", project_path)


def sanitize_generated_qgis_metadata(
    project_file: str,
    log: logging.Logger,
    extent_bbox: Optional[list] = None,
) -> None:
    """Fix generated QGIS projects for QFieldCloud compatibility.

    Applies compatibility corrections that generated projects can need:

    1. Removes dangling iccProfileId attachment refs - QGIS sometimes writes
       iccProfileId="attachment:///qt_temp-XXXX" into ProjectStyleSettings but
       never bundles the temp file. QFieldCloud rejects such refs even though
       QGIS/QField tolerate them.

    2. Ensures the tasks layer is represented in <layer-tree-group> when a
       ``<layername>tasks</layername>`` maplayer exists.

    3. Injects <mapcanvas name="theMapCanvas"> if absent - QFieldCloud's
       process_projectfile worker looks for this element to extract the project
       extent and background colour.

       * For ``.qgz`` projects, this usually needs ``extent_bbox`` to synthesize
         a canvas extent when absent.
       * For ``.qgs`` projects, QGIS typically writes mapcanvas already, but if
         missing and ``extent_bbox`` is provided this helper can still inject it.
    """
    project_path = Path(project_file)
    suffix = project_path.suffix.lower()

    if suffix == ".qgz":
        _sanitize_qgz_project(project_path, log, extent_bbox)
        return

    if suffix == ".qgs":
        _sanitize_qgs_project(project_path, log, extent_bbox)
        return

    log.debug(
        "Skipping metadata sanitize for unsupported project type: %s", project_path
    )
