import {
  Search as SearchIcon,
  Close as CloseIcon,
  Person as PersonIcon,
  Menu as MenuIcon,
  Link as LinkIcon,
  Lock as LockIcon,
  Add as AddIcon,
  FormatAlignCenter as FormatAlignCenterIcon,
  Remove as RemoveIcon,
  Description as DescriptionIcon,
  FileDownload as FileDownloadIcon,
  Bolt as BoltIcon,
  FormatListBulleted as ListViewIcon,
  Done as DoneIcon,
  Settings as SettingsIcon,
  KeyboardArrowUp as KeyboardArrowUpIcon,
  CropFree as CropFreeIcon,
  LegendToggle as LegendToggleIcon,
  Delete as DeleteIcon,
  Map as MapIcon,
  ArrowForwardIos as ArrowForwardIosIcon,
  ArrowBackIos as ArrowBackIosIcon,
  VisibilityOutlined as VisibilityOutlinedIcon,
  FileDownloadOutlined as FileDownloadOutlinedIcon,
  AccessTime as AccessTimeIcon,
  Check as CheckIcon,
  CloudUploadOutlined as CloudUploadOutlinedIcon,
  DeleteOutlined as DeleteOutlinedIcon,
  Undo as UndoIcon,
  Timeline as TimelineIcon,
  FormatBold as FormatBoldIcon,
  FormatItalic as FormatItalicIcon,
  StrikethroughS as StrikethroughSIcon,
  FormatListNumbered as FormatListNumberedIcon,
  Code as CodeIcon,
  Redo as RedoIcon,
  FormatQuote as FormatQuoteIcon,
  AddPhotoAlternateOutlined as ImageAddIcon,
  HorizontalRule as HorizontalRuleIcon,
  QrCode2Outlined as QrCode2OutlinedIcon,
  ChevronRight as ChevronRightIcon,
  ChevronLeft as ChevronLeftIcon,
  ExpandLess as ExpandLessIcon,
  ExpandMore as ExpandMoreIcon,
  CheckBox as CheckBoxIcon,
  CheckBoxOutlineBlank as CheckBoxOutlineBlankIcon,
  ManageAccountsOutlined as ManageAccountsOutlinedIcon,
  LogoutOutlined as LogoutOutlinedIcon,
  BarChartOutlined as BarChartOutlinedIcon,
  MapOutlined as MapOutlinedIcon,
  HistoryOutlined as HistoryOutlinedIcon,
  LockOutlined as LockOutlinedIcon,
  ContentCopy as ContentCopyIcon,
  InfoOutlined as InfoOutlineIcon,
  YouTube as YouTubeIcon,
  LinkedIn as LinkedInIcon,
  X as XIcon,
  Facebook as FacebookIcon,
  Instagram as InstagramIcon,
  GitHub as GitHubIcon,
  Assignment as AssignmentIcon,
  Warning as WarningIcon,
  OpenInNew as OpenInNewIcon,
  PlaceOutlined as PlaceOutlinedIcon,
} from '@mui/icons-material';
import LockPng from '@/assets/images/lock.png';
import RedLockPng from '@/assets/images/red-lock.png';
export default {
  DescriptionIcon,
  FileDownloadIcon,
  SearchIcon,
  CloseIcon,
  PersonIcon,
  MenuIcon,
  LinkIcon,
  LockIcon,
  AddIcon,
  FormatAlignCenterIcon,
  RemoveIcon,
  LockPng,
  RedLockPng,
  BoltIcon,
  ListViewIcon,
  DoneIcon,
  SettingsIcon,
  KeyboardArrowUpIcon,
  CropFreeIcon,
  LegendToggleIcon,
  DeleteIcon,
  MapIcon,
  ArrowForwardIosIcon,
  ArrowBackIosIcon,
  VisibilityOutlinedIcon,
  FileDownloadOutlinedIcon,
  AccessTimeIcon,
  CheckIcon,
  CloudUploadOutlinedIcon,
  DeleteOutlinedIcon,
  UndoIcon,
  TimelineIcon,
  FormatBoldIcon,
  FormatItalicIcon,
  StrikethroughSIcon,
  FormatListNumberedIcon,
  CodeIcon,
  RedoIcon,
  FormatQuoteIcon,
  ImageAddIcon,
  HorizontalRuleIcon,
  QrCode2OutlinedIcon,
  ChevronRightIcon,
  ChevronLeftIcon,
  ExpandLessIcon,
  ExpandMoreIcon,
  CheckBoxIcon,
  CheckBoxOutlineBlankIcon,
  ManageAccountsOutlinedIcon,
  LogoutOutlinedIcon,
  BarChartOutlinedIcon,
  MapOutlinedIcon,
  HistoryOutlinedIcon,
  LockOutlinedIcon,
  ContentCopyIcon,
  InfoOutlineIcon,
  YouTubeIcon,
  LinkedInIcon,
  XIcon,
  FacebookIcon,
  InstagramIcon,
  GitHubIcon,
  AssignmentIcon,
  WarningIcon,
  OpenInNewIcon,
  PlaceOutlinedIcon,
};
