# Copyright (c) Humanitarian OpenStreetMap Team
# This file is part of FMTM.
#
#     FMTM is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     FMTM is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with FMTM.  If not, see <https:#www.gnu.org/licenses/>.
#

networks:
  fmtm-net:
    name: fmtm-${GIT_BRANCH:-local}

services:
  central-tunnel:
    image: "docker.io/cloudflare/cloudflared:2024.10.1"
    depends_on:
      central:
        condition: service_healthy
    networks:
      - fmtm-net
    restart: "unless-stopped"
    command: tunnel --url http://central:8383

  button:
    image: "ghcr.io/hotosm/fmtm/frontend:button"
    build:
      context: ./src
      additional_contexts:
        - code=./contrib/tunnel/button
      dockerfile: Dockerfile.ui.debug
    volumes:
      - ./contrib/tunnel/button:/app
      - /app/node_modules/
    networks:
      - fmtm-net
    restart: "unless-stopped"
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/3001' || exit 1
      interval: 5s
      retries: 3
      start_period: 5s
      timeout: 5s

  button-tunnel:
    image: "docker.io/cloudflare/cloudflared:2024.10.1"
    depends_on:
      button:
        condition: service_healthy
    networks:
      - fmtm-net
    restart: "unless-stopped"
    command: tunnel --url http://button:3001
