name: Build ODK Images

on:
  # Push includes PR merge
  push:
    branches:
      - development
    paths:
      # Workflow is triggered only if odkcentral dir changes
      - "odkcentral/**"
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-odkcentral:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@main
    with:
      context: odkcentral/api
      dockerfile: odkcentral/api/Dockerfile
      image_tags: |
        "ghcr.io/hotosm/fmtm/odkcentral:${{ vars.ODK_CENTRAL_VERSION }}"
        "ghcr.io/hotosm/fmtm/odkcentral:latest"
      build_args: |
        ODK_CENTRAL_VERSION=${{ vars.ODK_CENTRAL_VERSION }}

  build-proxy:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@main
    with:
      context: odkcentral/proxy
      dockerfile: odkcentral/proxy/Dockerfile
      image_tags: |
        "ghcr.io/hotosm/fmtm/odkcentral-proxy:${{ vars.ODK_CENTRAL_VERSION }}"
        "ghcr.io/hotosm/fmtm/odkcentral-proxy:latest"
