name: 🔧 Build ODK Images

on:
  # Push includes PR merge
  push:
    branches:
      - dev
    paths:
      # Workflow is triggered only if odkcentral dir changes
      - "odkcentral/**"
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-odkcentral:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@3.3.2
    with:
      context: odkcentral/api
      image_tags: |
        "ghcr.io/${{ github.repository }}/odkcentral:v2025.2.1"
        "ghcr.io/${{ github.repository }}/odkcentral:latest"
      extra_build_args: |
        ODK_CENTRAL_TAG=v2025.2.0
      multi_arch: true

  build-odkcentral-ui:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@3.3.2
    with:
      context: odkcentral/ui
      image_tags: |
        "ghcr.io/${{ github.repository }}/odkcentral-ui:v2025.2.1"
        "ghcr.io/${{ github.repository }}/odkcentral-ui:latest"
      extra_build_args: |
        ODK_CENTRAL_TAG=v2025.2.0
      multi_arch: true
      # Allow usage of ADD directive in this specific use case
      skip_cve: "CKV_DOCKER_8,CKV_DOCKER_2,CKV_DOCKER_3,CKV_DOCKER_5,CKV_DOCKER_4"
