name: Build ODK Images

on:
  # Push includes PR merge
  push:
    branches:
      - development
    paths:
      # Workflow is triggered only if odkcentral dir changes
      - "odkcentral/**"
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-odkcentral:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@main
    with:
      context: odkcentral/api
      image_tags: |
        "ghcr.io/${{ github.repository }}/odkcentral:${{ vars.ODK_CENTRAL_TAG }}"
        "ghcr.io/${{ github.repository }}/odkcentral:latest"
      build_args: |
        ODK_CENTRAL_TAG=${{ vars.ODK_CENTRAL_TAG }}

  build-proxy:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@main
    with:
      context: odkcentral/proxy
      image_tags: |
        "ghcr.io/${{ github.repository }}/odkcentral-proxy:${{ vars.ODK_CENTRAL_TAG }}"
        "ghcr.io/${{ github.repository }}/odkcentral-proxy:latest"
