name: Build CI Img

on:
  # Push includes PR merge
  push:
    branches:
      - main
      - staging
      - development
    paths:
      # Workflow is triggered only if deps change
      - "src/backend/pyproject.toml"
      - "src/backend/Dockerfile"
  # Allow manual trigger
  workflow_dispatch:

jobs:
  extract-versions:
    uses: ./.github/workflows/r-extract_versions.yml

  backend-ci-build:
    uses: ./.github/workflows/r-build_backend.yml
    needs: [extract-versions]
    with:
      api_version: ${{ needs.extract-versions.outputs.api_version }}
      build_target: ci
      image_tags: |
        "ghcr.io/hotosm/fmtm/backend:${{ needs.extract-versions.outputs.api_version }}-ci-${{ github.ref_name }}"
        "ghcr.io/hotosm/fmtm/backend:ci-${{ github.ref_name }}"
