name: 📖 Publish Docs

on:
  push:
    paths:
      - docs/**
      - src/**
      - tasks/**
      - Justfile
      - mkdocs.yml
    branches: [dev]
  # Allow manual trigger (workflow_dispatch)
  workflow_dispatch:

jobs:
  pytest:
    uses: hotosm/gh-workflows/.github/workflows/just.yml@3.3.2
    with:
      environment: "test"
      command: "docs publish"
    secrets: inherit
