name: Publish Docs

on:
  push:
    paths:
      - docs/**
      - src/**
      - mkdocs.yml
    branches: [main]
  # Allow manual trigger (workflow_dispatch)
  workflow_dispatch:

jobs:
  build_doxygen:
    uses: hotosm/gh-workflows/.github/workflows/doxygen_build.yml@main
    with:
      cache_paths: |
        docs/apidocs
        docs/openapi.json
      cache_key: docs-build

  build_openapi_json:
    uses: hotosm/gh-workflows/.github/workflows/openapi_build.yml@main
    with:
      image: ghcr.io/hotosm/fmtm/backend:ci-${{ github.ref_name }}
      example_env_file_path: ".env.example"
      cache_paths: |
        docs/apidocs
        docs/openapi.json
      cache_key: docs-build

  publish_docs:
    uses: hotosm/gh-workflows/.github/workflows/mkdocs_build.yml@main
    needs:
      - build_doxygen
      - build_openapi_json
    with:
      image: ghcr.io/hotosm/fmtm/backend:ci-${{ github.ref_name }}
      cache_paths: |
        docs/apidocs
        docs/openapi.json
      cache_key: docs-build
