name: Publish Docs

on:
  push:
    paths:
      - docs/**
      - src/**
      - mkdocs.yml
    branches: [main]
  # Allow manual trigger (workflow_dispatch)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  get_cache_key:
    runs-on: ubuntu-latest
    steps:
      - run: echo "cache_key=docs-build-$(date --utc '+%V')" >> $GITHUB_ENV

  build_doxygen:
    uses: hotosm/gh-workflows/.github/workflows/doxygen_build.yml@main
    with:
      cache_paths: |
        docs/apidocs
      cache_key: ${{ env.cache_key }}

  build_openapi_json:
    uses: hotosm/gh-workflows/.github/workflows/openapi_build.yml@main
    with:
      image: ghcr.io/hotosm/fmtm/backend:ci-main
      example_env_file_path: ".env.example"
      cache_paths: |
        docs/openapi.json
      cache_key: ${{ env.cache_key }}

  publish_docs:
    uses: hotosm/gh-workflows/.github/workflows/mkdocs_build.yml@main
    needs: [build_doxygen, build_openapi_json]
    with:
      cache_paths: |
        docs/apidocs
        docs/openapi.json
      cache_key: ${{ env.cache_key }}
