name: PR

on:
  pull_request:
    branches:
      - main
      - staging
      - development
  # Allow manual trigger (workflow_dispatch)
  workflow_dispatch:

jobs:
  pytest:
    uses: ./.github/workflows/r-pytest.yml
    with:
      image_tag: ci-${{ github.base_ref }}
  frontend-main-tests:
    uses: ./.github/workflows/r-frontend_tests.yml
