name: 🧪 PR Tests Frontend

on:
  pull_request:
    branches:
      - main
      - staging
      - development
    # Workflow is triggered only if src/frontend changes
    paths:
      - src/frontend/**
  # Allow manual trigger (workflow_dispatch)
  workflow_dispatch:

jobs:
  unit-tests:
    uses: hotosm/gh-workflows/.github/workflows/test_pnpm.yml@2.0.5
    with:
      working_dir: src/frontend

  e2e-tests:
    uses: hotosm/gh-workflows/.github/workflows/test_compose.yml@2.0.5
    with:
      playwright: true
      cache_image: false
      compose_file: docker-compose.yml -f contrib/playwright/docker-compose.yml
      compose_service: ui-test
      cache_extra_imgs: |
        "docker.io/postgis/postgis:${{ vars.POSTGIS_TAG }}"
        "docker.io/minio/minio:${{ vars.MINIO_TAG }}"
        "ghcr.io/hotosm/fmtm/frontend:playwright-${{ vars.PLAYWRIGHT_TAG }}"
    secrets: inherit
