name: 🧪 PR Tests Frontend

on:
  pull_request:
    branches:
      - main
      - staging
      - dev
    # Workflow is triggered only if src/frontend changes
    paths:
      - src/frontend/**
  # Allow manual trigger (workflow_dispatch)
  workflow_dispatch:

jobs:
  unit-tests:
    uses: hotosm/gh-workflows/.github/workflows/test_pnpm.yml@3.2.3
    with:
      working_dir: src/frontend

  e2e-tests:
    uses: hotosm/gh-workflows/.github/workflows/test_compose.yml@3.2.3
    with:
      playwright: true
      cache_image: false
      compose_file: compose.yaml -f contrib/playwright/compose.yaml
      compose_service: ui-test
      cache_extra_imgs: |
        "ghcr.io/hotosm/postgis:${{ vars.POSTGIS_TAG }}"
        "docker.io/minio/minio:${{ vars.MINIO_TAG }}"
        "mcr.microsoft.com/playwright:${{ vars.PLAYWRIGHT_TAG }}"
    secrets: inherit
