name: 🧪 PR Test Backend

on:
  pull_request:
    branches:
      - main
      - staging
      - dev
    # Workflow is triggered only if src/backend changes
    paths:
      - src/backend/**
  # Allow manual trigger (workflow_dispatch)
  workflow_dispatch:

jobs:
  pytest:
    uses: hotosm/gh-workflows/.github/workflows/just.yml@3.3.2
    with:
      environment: "test"
      command: "test backend"
    secrets: inherit
