name: 🧪 PR Tests Frontend

on:
  pull_request:
    branches:
      - main
      - staging
      - development
    # Workflow is triggered only if src/frontend changes
    paths:
      - src/frontend/**
  # Allow manual trigger (workflow_dispatch)
  workflow_dispatch:

jobs:
  unit-tests:
    uses: hotosm/gh-workflows/.github/workflows/test_pnpm.yml@3.2.0
    with:
      working_dir: src/frontend

  e2e-tests:
    uses: hotosm/gh-workflows/.github/workflows/test_compose.yml@3.2.0
    with:
      playwright: true
      cache_image: false
      compose_file: compose.yaml -f contrib/playwright/compose.yaml
      compose_service: ui-test
      cache_extra_imgs: |
        "ghcr.io/hotosm/postgis:14-3.5-alpine"
        "ghcr.io/hotosm/postgis:16-3.5-alpine"
        "docker.io/minio/minio:RELEASE.2025-01-20T14-49-07Z"
        "mcr.microsoft.com/playwright:v1.48.1"
    secrets: inherit
