# FIXME is an automated publishing flow a bit over-complex for the monorepo setup?
# FIXME Is it even useful if we just publish manually periodically when stable?
# FIXME we should also add area-splitter if we decided on doing this

name: 🚩 Publish osm-fieldwork

on:
  #   release:
  #     types: [published]
  # Allow manual trigger (workflow_dispatch)
  workflow_dispatch:

jobs:
  do_nothing:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello
#   publish_to_pypi:
#     uses: hotosm/gh-workflows/.github/workflows/pypi_publish.yml@2.0.5
#     secrets:
#       PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
