name: Build Backend Imgs

on:
  workflow_call:
    paths:
      - src/backend/**
    inputs:
      api_version:
        required: true
        type: string
      build_target:
        required: true
        type: string
      image_tags:
        required: true
        type: string

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: src/backend
          target: ${{ inputs.build_target }}
          push: true
          tags: ${{ inputs.image_tags }}
          build-args: |
            APP_VERSION=${{ inputs.api_version }}
