name: Frontend Tests

on:
  workflow_call:

jobs:
  test:
    name: Run Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
          cache-dependency-path: "src/frontend/pnpm-lock.yaml"

      - name: Install dependencies
        working-directory: src/frontend
        run: pnpm install

      - name: Test Frontend
        working-directory: src/frontend
        run: pnpm run test
