name: Frontend Tests

on:
  workflow_call:

jobs:
  test:
    name: Run Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: |
            src/frontend/node_modules
          keys: node-modules-${{ env.cache_id }}
          restore-keys: |
            node-modules-

      - name: Test Frontend
        run: |
          cd src/frontend
          npm ci --only-dev
          npm run test
