name: pytest

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
      environment:
        required: false
        type: string

permissions:
  contents: read

jobs:
  run-pytest:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'test' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Environment to .env
        run: |
          echo "DEBUG=True" >> .env
          echo "LOG_LEVEL=DEBUG" >> .env
          echo "API_TAG_OVERRIDE=${{ inputs.image_tag }}" >> .env
          echo "FRONTEND_MAIN_URL=${{ vars.FRONTEND_MAIN_URL }}" >> .env
          echo "ODK_CENTRAL_URL=${{ vars.ODK_CENTRAL_URL }}" >> .env
          echo "ODK_CENTRAL_USER=${{ vars.ODK_CENTRAL_USER }}" >> .env
          echo "ODK_CENTRAL_PASSWD=${{ secrets.ODK_CENTRAL_PASSWD }}" >> .env
          echo "OSM_CLIENT_ID=${{ secrets.OSM_CLIENT_ID }}" >> .env
          echo "OSM_CLIENT_SECRET=${{ secrets.OSM_CLIENT_SECRET }}" >> .env
          echo "OSM_SECRET_KEY=${{ secrets.OSM_SECRET_KEY }}" >> .env
          cat .env

      # - uses: hotosm/gh-workflows/.github/workflows/image_cache.yml@main
      #   with:
      #     image_name: postgis/postgis:14-3.3-alpine

      - name: Run PyTest
        run: |
          docker compose run api \
            wait-for-it fmtm-db:5432 --strict \
            -- wait-for-it central:8383 --strict \
            -- pytest
