name: pytest

on:
  workflow_call:
    inputs:
      image_tag:
        description: "Optional image tag override."
        required: false
        type: string
        default: ci-development
      build_test_img:
        description: "Build an image prior to test, e.g. if new deps added."
        required: false
        type: boolean
        default: false
      environment:
        description: "The environment to use for testing."
        required: false
        type: string
        default: "test"

permissions:
  contents: read

jobs:
  backend-test-build:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@main
    if: ${{ inputs.build_test_img }}
    with:
      context: src/backend
      build_target: ci
      image_name: ghcr.io/${{ github.repository }}/backend
      build_args: |
        APP_VERSION=${{ github.ref_name }}
        COMMIT_REF=${{ github.sha }}
      # Build temp (workflow) cached image for PR, not in registry
      push: false
      cache: false
      multi_arch: false

  run-pytest:
    runs-on: ubuntu-latest
    needs: [backend-test-build]
    # Ensure it runs, even if build_test_img=false
    if: always()
    environment:
      name: ${{ inputs.environment}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: image-cache
        uses: actions/cache@v3
        with:
          path: /tmp/images
          key: image-cache-${{ runner.os }}

      - name: Save Local Images
        if: steps.image-cache.outputs.cache-hit != 'true'
        run: |
          # Function to pull and package Docker image
          function pull_and_package_image() {
            local image=$1
            echo "Processing image ${image}"
            docker pull "${image}"

            if [ $? -eq 0 ]; then
              img_underscores=${image//[:\/.]/_}
              echo "Packaging image to /tmp/images/${img_underscores}.tar"
              docker image save "${image}" --output "/tmp/images/${img_underscores}.tar"
            else
              echo "Failed to pull the image: ${image}"
            fi
          }

          # Make artifact dir
          mkdir -p /tmp/images

          images_array=(
            "docker.io/postgis/postgis:${{ vars.POSTGIS_TAG }}"
            "ghcr.io/hotosm/fmtm/odkcentral:${{ vars.ODK_CENTRAL_TAG }}"
            "ghcr.io/hotosm/fmtm/odkcentral-proxy:${{ vars.ODK_CENTRAL_TAG }}"
            "docker.io/minio/minio:${{ vars.MINIO_TAG }}"
          )

          # Iterate through dependency images
          for image in "${images_array[@]}"; do
            pull_and_package_image "$image"
          done

          # Cache backend build
          image=${{ needs.backend-test-build.outputs.image_name || inputs.image_tag }}
          pull_and_package_image "$image"

      - name: Load Cached Imgs
        if: steps.image-cache.outputs.cache-hit == 'true'
        run: |
          for image_tar in /tmp/images/*; do
              docker image load --input $image_tar || true
          done

      - name: Vars and Secrets to Env
        env:
          API_TAG_OVERRIDE: ${{ needs.backend-test-build.outputs.image_name || inputs.image_tag }}
          GIT_BRANCH: ${{ github.ref_name }}
          VARS_CONTEXT: ${{ toJson(vars) }}
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
        run: |
          to_envs() { jq -r "to_entries[] | \"\(.key)=\(.value)\""; }

          echo "API_TAG_OVERRIDE=${API_TAG_OVERRIDE}" >> $GITHUB_ENV
          echo "GIT_BRANCH=${GIT_BRANCH}" >> $GITHUB_ENV
          echo "${VARS_CONTEXT}" | to_envs >> $GITHUB_ENV
          echo "${SECRETS_CONTEXT}" | to_envs >> $GITHUB_ENV

      - name: Create .env file
        run: env > .env

      - name: Run PyTest
        run: |
          docker compose run api \
            wait-for-it fmtm-db:5432 --strict \
            -- wait-for-it central:8383 --strict --timeout=30 \
            -- pytest
