name: pytest

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
      environment:
        required: false
        type: string

permissions:
  contents: read

jobs:
  run-pytest:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'test' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Environment to .env
        env:
          DEBUG: True
          LOG_LEVEL: DEBUG
          API_TAG_OVERRIDE: ${{ inputs.image_tag }}
          ODK_CENTRAL_URL: ${{ vars.ODK_CENTRAL_URL }}
          ODK_CENTRAL_USER: ${{ vars.ODK_CENTRAL_USER }}
          ODK_CENTRAL_PASSWD: ${{ secrets.ODK_CENTRAL_PASSWD }}
          OSM_CLIENT_ID: ${{ secrets.OSM_CLIENT_ID }}
          OSM_CLIENT_SECRET: ${{ secrets.OSM_CLIENT_SECRET }}
          OSM_SECRET_KEY: ${{ secrets.OSM_SECRET_KEY }}

        run: |
          echo "DEBUG=${DEBUG}" >> .env
          echo "LOG_LEVEL=${LOG_LEVEL}" >> .env
          echo "API_TAG_OVERRIDE=${API_TAG_OVERRIDE}" >> .env
          echo "ODK_CENTRAL_URL=${ODK_CENTRAL_URL}" >> .env
          echo "ODK_CENTRAL_USER=${ODK_CENTRAL_USER}" >> .env
          echo "ODK_CENTRAL_PASSWD=${ODK_CENTRAL_PASSWD}" >> .env
          echo "OSM_CLIENT_ID=${OSM_CLIENT_ID}" >> .env
          echo "OSM_CLIENT_SECRET=${OSM_CLIENT_SECRET}" >> .env
          echo "OSM_SECRET_KEY=${OSM_SECRET_KEY}" >> .env

      - name: Start Services
        run: |
          cd src/backend
          docker compose up api --detach

      - name: Run pytest
        run: docker exec fmtm_api pytest
