name: pytest

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
      environment:
        required: false
        type: string

permissions:
  contents: read

jobs:
  postgis-img-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Set PostGIS Img Cache
        id: cache-img-postgis
        uses: actions/cache@v3
        with:
          path: ci/cache/images/postgis:14-3.3-alpine.tar
          key: img-cache
      - name: Update PostGIS Img Cache
        if: steps.cache-img-postgis.outputs.cache-hit != 'true'
        run: |
          docker pull postgis/postgis:14-3.3-alpine
          mkdir -p ci/cache/images
          docker image save postgis/postgis:14-3.3-alpine \
            --output ./ci/cache/images/postgis:14-3.3-alpine.tar

  odk-img-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Set ODK Img Cache
        id: cache-img-odk
        uses: actions/cache@v3
        with:
          path: ci/cache/images/odkcentral:v2023.2.1.tar
          key: img-cache
      - name: Update ODK Img Cache
        if: steps.cache-img-odk.outputs.cache-hit != 'true'
        run: |
          docker pull ghcr.io/hotosm/fmtm/odkcentral:v2023.2.1
          mkdir -p ci/cache/images
          docker image save ghcr.io/hotosm/fmtm/odkcentral:v2023.2.1 \
            --output ./ci/cache/images/odkcentral:v2023.2.1.tar

  odk-proxy-img-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Set ODK Proxy Img Cache
        id: cache-img-odk-proxy
        uses: actions/cache@v3
        with:
          path: ci/cache/images/odkcentral-proxy:latest.tar
          key: img-cache
      - name: Update ODK Proxy Img Cache
        if: steps.cache-img-odk-proxy.outputs.cache-hit != 'true'
        run: |
          docker pull ghcr.io/hotosm/fmtm/odkcentral-proxy:latest
          mkdir -p ci/cache/images
          docker image save ghcr.io/hotosm/fmtm/odkcentral-proxy:latest \
            --output ./ci/cache/images/odkcentral-proxy:latest.tar

  run-pytest:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment || 'test' }}
    needs:
      - postgis-img-cache
      - odk-img-cache
      - odk-proxy-img-cache

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Img Caches
        id: restore-imgs
        uses: actions/cache@v3
        with:
          path: |
            ci/cache/images/postgis:14-3.3-alpine.tar
            ci/cache/images/odkcentral:v2023.2.1.tar
            ci/cache/images/odkcentral-proxy:latest.tar
          key: img-cache

      - name: Load Cached Imgs
        if: steps.restore-imgs.outputs.cache-hit == 'true'
        run: |
          docker image load --input ./ci/cache/images/postgis:14-3.3-alpine.tar || true
          docker image load --input ./ci/cache/images/odkcentral:v2023.2.1.tar || true
          docker image load --input ./ci/cache/images/odkcentral-proxy:latest.tar || true

      - name: Environment to .env
        env:
          DEBUG: True
          LOG_LEVEL: DEBUG
          API_TAG_OVERRIDE: "${{ inputs.image_tag }}"
          FRONTEND_MAIN_URL: "${{ vars.FRONTEND_MAIN_URL }}"
          ODK_CENTRAL_URL: "${{ vars.ODK_CENTRAL_URL }}"
          ODK_CENTRAL_USER: "${{ vars.ODK_CENTRAL_USER }}"
          ODK_CENTRAL_PASSWD: "${{ secrets.ODK_CENTRAL_PASSWD }}"
          OSM_CLIENT_ID: "${{ secrets.OSM_CLIENT_ID }}"
          OSM_CLIENT_SECRET: "${{ secrets.OSM_CLIENT_SECRET }}"
          OSM_SECRET_KEY: "${{ secrets.OSM_SECRET_KEY }}"
        run: |
          echo "DEBUG=${DEBUG}" >> .env
          echo "LOG_LEVEL=${LOG_LEVEL}" >> .env
          echo "API_TAG_OVERRIDE=${API_TAG_OVERRIDE}" >> .env
          echo "FRONTEND_MAIN_URL=${FRONTEND_MAIN_URL}" >> .env
          echo "ODK_CENTRAL_URL=${ODK_CENTRAL_URL}" >> .env
          echo "ODK_CENTRAL_USER=${ODK_CENTRAL_USER}" >> .env
          echo "ODK_CENTRAL_PASSWD=${ODK_CENTRAL_PASSWD}" >> .env
          echo "OSM_CLIENT_ID=${OSM_CLIENT_ID}" >> .env
          echo "OSM_CLIENT_SECRET=${OSM_CLIENT_SECRET}" >> .env
          echo "OSM_SECRET_KEY=${OSM_SECRET_KEY}" >> .env

      - name: Run PyTest
        run: |
          docker compose run api \
            wait-for-it fmtm-db:5432 --strict \
            -- wait-for-it central:8383 --strict \
            -- pytest
