name: 🔧 Build Tag & Release Images

on:
  # All releases
  release:
    types: [published]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  backend-build:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@3.2.2
    with:
      context: src
      dockerfile: backend/Dockerfile
      build_target: prod
      image_name: ghcr.io/${{ github.repository }}/backend
      multi_arch: true
# Frontend is not built as build variables are required
